name: Test

permissions: write-all

on:
  workflow_call:
    secrets:
      MY_GITHUB_TOKEN:
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

  test_and_documentation:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov graphviz python3-pip

      - name: Install doxygen
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_11_0/doxygen-1.11.0.linux.bin.tar.gz
          tar -xzf doxygen-1.11.0.linux.bin.tar.gz
          cd doxygen-1.11.0
          sudo make
          sudo make install
          cd ..
          sudo rm -rf doxygen-1.11.0 doxygen-1.11.0.linux.bin.tar.gz

      - name: Install python dependencies
        run: |
          sudo pip install -U rosdep
          pip install colcon-common-extensions colcon-lcov-result vcstool mike python-markdown-math

      - name: Create the src dir
        run: |
          mkdir -p ${{ github.workspace }}/src/${{ github.event.repository.name }}

      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: src/${{ github.event.repository.name }}/

      - name: Parse dependencies.repos and insert token
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          if [ -f src/${{ github.event.repository.name }}/dependencies.repos ]; then
            sed -i "s|https://|https://${GH_TOKEN}@|g" src/${{ github.event.repository.name }}/dependencies.repos
          fi

      - name: Install dependencies with vcs
        run: |
          if [ -f src/${{ github.event.repository.name }}/dependencies.repos ]; then
            vcs import src < src/${{ github.event.repository.name }}/dependencies.repos
          fi

      - name: Install dependencies with rosdep
        run: |
          sudo apt update && sudo apt install curl -y
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src --rosdistro humble

      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --cmake-args -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage -fno-elide-constructors -fno-default-inline -ffunction-sections' -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'

      - name: Test and generate code coverage
        run: |
          source /opt/ros/humble/setup.bash
          colcon lcov-result --initial --packages-select ${{ github.event.repository.name }}
          colcon test --event-handlers console_direct+ --packages-select ${{ github.event.repository.name }} --return-code-on-test-failure
          colcon lcov-result --filter */test/* --packages-select ${{ github.event.repository.name }}

      - name: Get documentation directory for deployment
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "DEPLOY_REF=PR-${{ github.event.number }}" >> $GITHUB_ENV
          else
            cd ${{ github.workspace }}/src/${{ github.event.repository.name }}
            git fetch --tags
            TAG=$(git describe --tags --abbrev=0)
            VERSION=${TAG%.*}
            echo "DEPLOY_REF=${VERSION}" >> $GITHUB_ENV
          fi

      - name: Generate example documentation
        run: |
          git clone https://github.com/Robotsix-UAV/example_cpp_to_md
          python3 example_cpp_to_md/example_cpp_to_md.py ${{ github.workspace }}/src/${{ github.event.repository.name }}/examples ${{ github.workspace }}/src/${{ github.event.repository.name }}/docs

      - name: Create and push with mike
        run: |
          git config --global user.name robotsix_bot
          git config --global user.email robotsix_bot@noreply.com
          cd ${{ github.workspace }}/src/${{ github.event.repository.name }}
          git fetch origin gh-pages --depth=1 || true
          mike deploy ${{ env.DEPLOY_REF }} -b gh-pages -p

      - name: Build rosdoc2 Documentation
        shell: bash
        run: |
          git clone https://github.com/ros-infrastructure/rosdoc2
          cd rosdoc2
          pip install .
          cd ${{ github.workspace }}
          rosdoc2 build -p ${{ github.workspace }}/src/${{ github.event.repository.name }}
          cp /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/docs_build/${{ github.event.repository.name }}/${{ github.event.repository.name }}-public-cc-api/doxygen-warnings.log . || true

      - name: Display doxygen warnings
        run: |
          if [ -f doxygen-warnings.log ]; then
            cat doxygen-warnings.log
          fi

      - name: Parse and Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = 'doxygen-warnings.log';

            // Check if the log file exists and is not empty
            if (fs.existsSync(path) && fs.statSync(path).size > 0) {
              const warnings = fs.readFileSync(path, 'utf8').trim().split('\n');
              let commentBody = "### :warning: Doxygen Warnings Found\n";
              commentBody += "Here are the details of the warnings:\n```\n";

              warnings.forEach(warning => {
                commentBody += `${warning}\n`;
              });

              commentBody += "```\nPlease review the warnings and make necessary changes.";

              // Create a comment on the PR
              console.log('Posting comment with Doxygen warnings');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number, // This assumes the action is triggered by a pull_request event
                body: commentBody
              });
            } else {
              console.log('No Doxygen warnings log file found or the file is empty.');
            }

      - name: Clone and checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ${{ github.event.repository.name }}

      - name: Fetch gh-pages branch
        run: |
          cd ${{ github.event.repository.name }}
          git fetch origin gh-pages --depth=1

      - name: Copy lcov results
        run: |
          cd ${{ github.event.repository.name }}
          mkdir -p ${{ env.DEPLOY_REF }}
          cp -r ${{ github.workspace }}/lcov ${{ env.DEPLOY_REF }}

      - name: Generate badge
        run: |
          git clone https://github.com/damien-robotsix/lcov-badger.git
          python3 lcov-badger/lcov-badger.py ${{ github.event.repository.name }}/${{ env.DEPLOY_REF }}/lcov/total_coverage.info ${{ github.event.repository.name }}/${{ env.DEPLOY_REF }}/lcov/badge.svg

      - name: Copy generated documentation
        run: |
          cd ${{ github.event.repository.name }}
          mkdir -p ${{ env.DEPLOY_REF }}/dev
          cp -r ${{ github.workspace }}/docs_output/${{ github.event.repository.name }} ${{ env.DEPLOY_REF }}/dev

      - name: Push changes to gh-pages squashing commits
        run: |
          cd ${{ github.event.repository.name }}
          git add .
          git commit -m "Documentation deployment"
          git reset $(git commit-tree HEAD^{tree} -m "gh-pages")
          git remote set-url --push origin https://$damien-robotsix:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin gh-pages
