name: Delete old workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  del_runs:
    name: Delete old workflow
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 1
